# Generated by Django 4.1.7 on 2023-04-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
